version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=cooperfilme
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json

  db:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
